version: '3'
services:
  # In Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@postgres/
  # Outside Docker
  # - TEST_POSTGRES_URI=postgres://prisma:prisma@localhost:5432/

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  prisma:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgres://prisma:prisma@postgres/
    ports:
      - '4000:4000'

volumes:
  postgres:
