service:
  name: jobs-api

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    handler: src/handlers/graphql.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
  playground:
    handler: src/handlers/graphql.playground
    events:
    - http:
        path: /
        method: get
        cors: true